# Generated by Django 5.0.6 on 2024-06-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_franchise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Franchise',
            new_name='Feedback',
        ),
    ]
