# Generated by Django 5.0.6 on 2024-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_cream_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_recipe_name', models.CharField(max_length=100)),
                ('ice_cream_recipe_discription', models.TextField()),
                ('ice_cream_recipe_image', models.ImageField(upload_to='ice_cream_recipe_img')),
            ],
        ),
    ]
