# Generated by Django 5.0.6 on 2024-07-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ice_cream_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ice_cream_Recipe',
            new_name='Icecream_Recipe',
        ),
    ]
