# Generated by Django 5.0.6 on 2024-07-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_ice_cream_recipe_icecream_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icecream_Recipe',
        ),
    ]
