# Generated by Django 5.0.6 on 2024-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_icecream_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_name', models.CharField(max_length=100)),
                ('icecream_description', models.TextField()),
                ('icecream_image', models.ImageField(upload_to='Ice-cream-images')),
            ],
        ),
    ]
