# Generated by Django 5.0.6 on 2024-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_icecream_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_name', models.CharField(max_length=100)),
                ('ice_discription', models.TextField()),
                ('ice_image', models.ImageField(upload_to='icecream')),
            ],
        ),
        migrations.DeleteModel(
            name='Icecream_recipe',
        ),
    ]
