# Generated by Django 5.0.6 on 2024-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ice_recipe_delete_icecream_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ice_recipe',
            name='ice_image',
            field=models.ImageField(upload_to='ice_cream_pictures'),
        ),
    ]
